// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo7I17Ii7Tqj3KdzMmzEdTj6eIUs4JbzQ',
    appId: '1:395010881499:web:9e245fa3b8ca7b025399fe',
    messagingSenderId: '395010881499',
    projectId: 'recipe-sharing-1a496',
    authDomain: 'recipe-sharing-1a496.firebaseapp.com',
    storageBucket: 'recipe-sharing-1a496.firebasestorage.app',
    measurementId: 'G-37TJ68QG92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiuSz1jyg3ZPrZdBQYm-KmfzgxLzFK330',
    appId: '1:395010881499:android:c2ebd12ee5a28e9e5399fe',
    messagingSenderId: '395010881499',
    projectId: 'recipe-sharing-1a496',
    storageBucket: 'recipe-sharing-1a496.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAq7VrCmEWwZInAbu8zuO3LViTsfCEpbI',
    appId: '1:395010881499:ios:212324df1bbaeb1d5399fe',
    messagingSenderId: '395010881499',
    projectId: 'recipe-sharing-1a496',
    storageBucket: 'recipe-sharing-1a496.firebasestorage.app',
    iosBundleId: 'com.example.recipeSharing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAq7VrCmEWwZInAbu8zuO3LViTsfCEpbI',
    appId: '1:395010881499:ios:212324df1bbaeb1d5399fe',
    messagingSenderId: '395010881499',
    projectId: 'recipe-sharing-1a496',
    storageBucket: 'recipe-sharing-1a496.firebasestorage.app',
    iosBundleId: 'com.example.recipeSharing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo7I17Ii7Tqj3KdzMmzEdTj6eIUs4JbzQ',
    appId: '1:395010881499:web:e26d9b2c33805cdc5399fe',
    messagingSenderId: '395010881499',
    projectId: 'recipe-sharing-1a496',
    authDomain: 'recipe-sharing-1a496.firebaseapp.com',
    storageBucket: 'recipe-sharing-1a496.firebasestorage.app',
    measurementId: 'G-CKK8KW9TNH',
  );
}
